# preload = ~/.config/backgrounds/spiderman.JPG
# wallpaper = , ~/.config/backgrounds/spiderman.JPG

wallpaper {
    monitor = 
    # path = ~/.config/backgrounds/spiderman.JPG
    path = ~/.config/backgrounds/frog.png
    fit_mode = cover
}
